version: "3.2"
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    environment:
      - WEBDRIVER_URL="http://selenium:4444/wd/hub"
      - PLAYWRIGHT_DRIVER_URL="ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true"
    ports:
      - "5000:5000"
    volumes:
      - ./changedetection-data:/datastore
    restart: unless-stopped
    depends_on:
      - selenium
      - playwright-chrome

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    #shm_size: "2g"
    restart: unless-stopped

  playwright-chrome:
    image: browserless/chrome:latest
    container_name: playwright-chrome
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
    ports:
      - "3000:3000"
    restart: unless-stopped
